[10.0] [WIP] [NEW] Module auth_dynamic_groups_contract.
OCA/server-auth pull request #117
Opened 2019-07-09 22:21 UTC by NL66278

Add users to groups based on their active contracts.

2019-07-10 06:52 UTC, hbrunn requested changes
I think there's arguments to put this into the contract repo, but also for putting it here

2019-07-10 06:52 UTC, hbrunn commented on auth_dynamic_groups_contract/readme/USAGE.rst
> +We iwant to have a group called `Our Newsletter` that should contain all
typo

2019-07-10 06:52 UTC, hbrunn commented on auth_dynamic_groups_contract/models/res_groups.py
> +                "user.has_group_contract(dynamic_group)"
as the UI doesn't force the user to have `is_dynamic` checked, I'd propose to set this flag here unconditionally

2019-07-10 06:52 UTC, hbrunn commented on auth_dynamic_groups_contract/views/res_groups.xml
> +                <field name="is_contract_based" />
or make this only visible when `is_dynamic` is checked

2019-07-10 06:52 UTC, hbrunn commented on auth_dynamic_groups_contract/views/res_groups.xml
> +            </field>
I'd suggest to make the condition also readonly, we don't want the user to fiddle with the condition then

2019-07-10 16:11 UTC, NL66278 commented
@hbrunn I took up your requests, but introduced more changes also in the base module, to make tests pass and improve performance.

Still will do some more changes, so no need to merge now, even if you are satisfied with the changes so far...

2019-10-15 15:21 UTC, NL66278 commented
This module is replaced by the more extensive (and flexible) code here: https://github.com/OCA/server-auth/pull/118

2019-10-15 15:21 UTC, closed without merging