changed param name
OCA/server-auth pull request #186
Opened 2020-04-17 20:58 UTC by acarmisc

Using the module as is doesn't works against fresh Keycloak setup. 
Validation request response is `400 Bad Request` and further description say the token is missing so I've changed the parameter

2020-05-29 10:25 UTC, gurneyalex commented
hello @acarmisc thanks for your contribution.

Do you know which versions of keycloak need this fix?

2020-06-02 10:31 UTC, simahawk commented
@acarmisc can you answer @gurneyalex 's question?

2020-06-02 12:02 UTC, acarmisc commented
sorry, I've missed the notification 🤷‍♂️ 

I got it with 10.0.0

2020-06-02 12:47 UTC, simahawk requested changes
AFAIS this would break it w/ older versions.
I would add a `version` field to the [provider](https://github.com/OCA/server-auth/blob/10.0/auth_keycloak/models/auth_oauth.py) and use the right key based on it.

2020-06-02 12:51 UTC, acarmisc commented
@simahawk I haven't check other versions, so it sounds correct... what if we add a field `token_key` instead of a `version` with a default to `token` ?

2020-06-02 13:04 UTC, simahawk commented
> @simahawk I haven't check other versions, so it sounds correct... what if we add a field `token_key` instead of a `version` with a default to `token` ?

I thought about it but we might need other hacks based on versions. 
Plus, this should not be something that user can/should change IMO.

Ideally we can use components to lookup for handlers by version in a smart way but at this stage is not really needed.
Let's keep it simple and add a `_auth_token_key()` method and put an IF inside it.

2021-11-03 23:23 UTC, bodedra reviewed
I tried with original following code in Odoo14 EE

    data={'token': access_token},

It is working fine.

2022-03-11 12:58 UTC, gurneyalex commented
@acarmisc  any news on this one?

2022-08-14 12:12 UTC, closed without merging