[14.0][FIX] password_security: 2FA workflow not being considered properly
OCA/server-auth pull request #335
Opened 2022-01-21 14:36 UTC by BT-cjimeno

When a user with 2FA enabled tried to log in, the user whose password expiration was being checked
was not the actual user logging in, instead it was OdooBot. Some changes were introduced to have
the 2fa module (auth_totp) into account.

Fixes #333

2022-01-21 14:40 UTC, BT-aestebanez requested changes

2022-01-21 14:40 UTC, BT-aestebanez commented on password_security/__manifest__.py
> +        "auth_totp"
Add "," at the end to ease traceability

2022-01-21 14:40 UTC, BT-aestebanez commented on password_security/__manifest__.py
> +        "auth_totp"
Add a comment explaining why you added this dependency

2022-01-21 14:57 UTC, BT-aestebanez approved these changes

2022-01-21 15:29 UTC, BT-aestebanez approved these changes

2022-01-27 08:29 UTC, BT-cjimeno commented
@dreispt , @Chandresh-SerpentCS Hi, would you have time for a review? Thanks!

2022-07-27 06:43 UTC, BT-cjimeno commented
@dreispt @Chandresh-OSI Hi, would you have time for a review? Thanks!

2022-07-27 07:03 UTC, BT-cjimeno commented
Hi @dreispt , could you please add the "no stale" label to this PR? Thanks!

2023-01-08 12:10 UTC, closed without merging