[15.0][ADD] auth_signup_partner_company
OCA/server-auth pull request #468
Opened 2023-01-30 05:23 UTC by AungKoKoLin1997

@qrtl

2023-01-30 06:19 UTC, yostashiro requested changes
Can you please add some tests.

2023-01-30 06:19 UTC, yostashiro commented on auth_signup_partner_company/models/res_users.py
> +        return user
```suggestion
    def _create_user_from_template(self, values):
        values["company_ids"] = [self.env.company.id]
        values["company_id"] = self.env.company.id
        return super()._create_user_from_template(values)

    def _signup_create_user(self, values):
        user = super()._signup_create_user(values)
        user.partner_id.company_id = self.env.company
        return user
```
Can you try and see if this works fine.

2023-01-30 06:19 UTC, yostashiro commented on auth_signup_partner_company/readme/DESCRIPTION.rst
> +This module assigns company to the newly created user and its partner.
```suggestion
This module assigns company to the user and its partner newly created through portal signup.

Odoo's standard behavior when a new portal user signs up:

* User's company is taken from the template user.
* Partner which links to the new user does not have a company assigned.

This behavior is problematic under multi-company, multi-website settings where partners
should be seggregated between the companies, and this module intends to fix this issue.
```

2023-01-30 09:58 UTC, kanda999 commented
Function review: it worked as expected.

2023-01-30 10:03 UTC, kanda999 approved these changes

2023-02-05 15:36 UTC, yostashiro reviewed
Just from the preference of not adding unnecessary contexts to the test data.

2023-02-05 15:36 UTC, yostashiro commented on auth_signup_partner_company/tests/test_auth_signup_partner_company.py
> +        )
```suggestion
        self.company_1 = self.env.company
        self.company_2 = self.env["res.company"].create({"name": "company 2"})
```

Let's remove the attributes not used in the test.

2023-02-05 15:36 UTC, yostashiro commented on auth_signup_partner_company/tests/test_auth_signup_partner_company.py
> +        self.assertEqual(user.partner_id.company_id, self.company_jpy)
```suggestion
    def test_auth_signup_company(self):
        self.assertEqual(self.env.company, self.company_1)
        self.env["res.users"].signup(
            {"name": "test 1", "login": "test1@gmail.com", "password": "123"}
        )
        user = self.env["res.users"].search([("login", "=", "test1@gmail.com")])
        self.assertEqual(user.company_id, self.company_1)
        self.assertEqual(user.partner_id.company_id, self.company_1)

        # Switch to another company and sign up.
        self.env.company = self.company_2
        self.env["res.users"].signup(
            {"name": "test 2", "login": "test2@gmail.com", "password": "123"}
        )
        user = self.env["res.users"].search([("login", "=", "test2@gmail.com")])
        self.assertEqual(user.company_id, self.company_2)
        self.assertEqual(user.partner_id.company_id, self.company_2)
```

2023-02-06 00:46 UTC, yostashiro approved these changes
Code review. LGTM. 👍

2023-03-20 09:37 UTC, dreispt commented
/ocabot merge nobump

2023-03-20 09:42 UTC, merged