[15.0][FIX] password_security: correctly look at previous password history
OCA/server-auth pull request #494
Opened 2023-03-06 10:29 UTC by astirpe

Fixes password history issue https://github.com/OCA/server-auth/issues/89 for V15.
This is the porting of the fix discussed in https://github.com/OCA/server-auth/pull/448 and includes the tests written by @amh-mw

2023-03-06 13:53 UTC, amh-mw requested changes

2023-03-06 13:53 UTC, amh-mw commented on password_security/models/res_users.py
> +                recent_passes = self.env["res.users.pass.history"]
I personally prefer to see .browse() after the model reference, as I think it's a more obviously understandable idiom, but I understand that they are synonyms.

```
recent_passes = self.env["res.users.pass.history"].browse()
```

2023-03-06 13:53 UTC, amh-mw commented on password_security/tests/test_password_history.py
> +        self.assertEqual(len(user.password_history_ids), 4)
To get the last piece of code coverage:

```python
        user.company_id.password_history = -1
        with self.assertRaises(UserError):
            user.write({"password": "admin"})
```

2023-03-06 14:08 UTC, astirpe commented on password_security/tests/test_password_history.py
> +        self.assertEqual(len(user.password_history_ids), 4)
Done, thank you!

2023-03-06 14:23 UTC, amh-mw approved these changes
LGTM @OCA/tools-maintainers

2023-03-06 14:25 UTC, amh-mw commented
@ivantodorovich Mind reviewing this fix for #448?

2023-07-02 13:01 UTC, thomaspaulb approved these changes

2023-07-02 13:02 UTC, thomaspaulb commented
/ocabot merge patch

2023-07-02 13:05 UTC, merged