[16.0][mig] auth_session_timeout: Migration to 16.0
OCA/server-auth pull request #524
Opened 2023-06-16 04:19 UTC by dsolanki-initos

2023-06-16 06:53 UTC, sbidoul commented
/ocabot migration auth_session_timeout

2023-07-02 14:16 UTC, thomaspaulb requested changes

2023-07-02 14:16 UTC, thomaspaulb commented on auth_session_timeout/models/res_users.py
> +        if terminated and tools.config["test_enable"]:
This doesn't look right - why doesn't the Exception need to be raised in normal Odoo operation?

2023-07-02 14:17 UTC, thomaspaulb requested changes

2023-07-02 14:17 UTC, thomaspaulb commented on README.md
> +[auth_session_timeout](auth_session_timeout/) | 16.0.1.0.0 |  | This module disable all inactive sessions since a given delay
This causes the PR to have a conflict

2023-07-02 14:17 UTC, thomaspaulb commented
This PR is a duplicate of https://github.com/OCA/server-auth/pull/507

2023-07-03 07:16 UTC, dsolanki-initos commented
> This PR is a duplicate of #507

Hello @thomaspaulb, I'm closing this PR.

2023-07-03 07:16 UTC, closed without merging