17.0 mig base user show email
OCA/server-auth pull request #605
Opened 2024-01-22 16:37 UTC by lav-adhoc

2024-10-18 17:05 UTC, lav-adhoc commented
@sbidoul 
Hello, can you re-open this pr and review it? thanks

2024-10-23 14:25 UTC, lav-adhoc commented
@pedrobaeza hi Pedro, can you re-open this pr and review it? thanks

2024-10-23 14:27 UTC, pedrobaeza commented
I'm not able to re-open it, sorry.

2024-10-23 14:28 UTC, pedrobaeza commented
/ocabot migration base_user_show_email

2024-10-23 15:02 UTC, lav-adhoc commented
@pedrobaeza @sbidoul thanks. what i have to do with the error in the coverage? Add some tests?

2024-10-23 15:04 UTC, pedrobaeza commented
Codecov is not mandatory. It's just a metric to show the code not covered by tests (and sometimes lies).

2024-10-23 15:19 UTC, lef-adhoc approved these changes

2024-10-23 15:20 UTC, matiasperalta1 approved these changes

2024-10-24 13:42 UTC, lav-adhoc commented
@sbidoul hi, can you merge it? thanks

2024-11-12 15:52 UTC, lav-adhoc commented
@pedrobaeza  hi, can you merge it? thanks

2024-11-12 15:58 UTC, pedrobaeza requested changes
It contains the infamous .deb package that must be removed, and the changes in README.rst are not in the proper commit. Please redo the migration again. At the end, it's only to switch 16 to 17.

2025-04-20 12:16 UTC, closed without merging