[16.0][MIG] impersonate_login: backport from V17 to V16
OCA/server-auth pull request #683
Opened 2024-08-29 16:52 UTC by astirpe

2024-08-29 19:43 UTC, StefanRijnhart approved these changes
Thanks!

2024-08-30 06:57 UTC, CasVissers-360ERP approved these changes

2024-08-30 07:01 UTC, CasVissers-360ERP commented
Tested / functional review.

2024-09-01 06:35 UTC, Kev-Roche requested changes
@astirpe, sincerely thank you to bring this module alive and fix it from the PR in V14 !
I have a question, in my original PR, I had css to visually show when we are logged with an impersonate user. Why not keep it ?

2024-09-01 06:35 UTC, Kev-Roche commented on impersonate_login/models/impersonate_log.py
> +        comodel_name="res.partner",
```suggestion
        comodel_name="res.users",
```

2024-09-01 07:34 UTC, astirpe commented on impersonate_login/models/impersonate_log.py
> +        comodel_name="res.partner",
Thank you!

2024-09-01 07:43 UTC, astirpe commented
@Kev-Roche Thank you!
Porting the css needed also the porting of the rest of the js logic, it was taking too much time to me. I was more focused to make this module just working in V17. But I think the css part is an important usability feature. Is it maybe something you can implement?

2024-09-01 08:09 UTC, Kev-Roche approved these changes

2024-09-01 08:10 UTC, Kev-Roche commented
> @Kev-Roche Thank you! Porting the css needed also the porting of the rest of the js logic, it was taking too much time to me. I was more focused to make this module just working in V17. But I think the css part is an important usability feature. Is it maybe something you can implement?

Ok, I'll work on this part.

2024-09-04 04:46 UTC, rvalyi approved these changes

2024-09-04 04:48 UTC, rvalyi commented
/ocabot merge nobump

2024-09-04 04:55 UTC, merged