[14.0] add auth_res_users_apikeys_server_env
OCA/server-auth pull request #688
Opened 2024-09-06 14:27 UTC by petrus-v

Allow to configure one API key scoped per environment

2024-09-12 06:28 UTC, damdam-s approved these changes

2024-09-13 08:38 UTC, barkat-matthias approved these changes
Really nice work ! LGTM

2024-09-13 12:43 UTC, amh-mw requested changes
Commit message should prefixed without [14.0] and with [ADD] per [coding standards](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message).

2024-09-13 14:37 UTC, petrus-v commented
> Commit message should prefixed without [14.0] and with [ADD] per [coding standards](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message).

oups, thanks for your attention :eyes:

2025-02-16 12:17 UTC, closed without merging