[17.0][MIG] auth_oauht_multi_token: Migration to 17.0
OCA/server-auth pull request #694
Opened 2024-09-24 04:36 UTC by timnis

Based on https://github.com/OCA/server-auth/pull/678 and thanks to [tb-flyt](https://github.com/tb-flyt)

Tried to follow instructions and hopefully I got it right 😃

2024-09-24 07:03 UTC, ap-wtioit commented
Can you please remove the [pandoc-3.4-1-amd64.deb](https://github.com/OCA/server-auth/pull/694/files#diff-1ffd63f3f64b165d3084c92a3713f05aaa0100e85d11f68f2a0fd747a1ece068) file.

2024-09-24 07:12 UTC, timnis commented
@ap-wtioit now pandoc-3.4-1-amd64.deb removed

2024-09-30 08:57 UTC, CRogos commented
It is important to squash the *.deb removal commit with the commit, where the file was added. Otherwise this large file stays in the git repository.... in this case the commit needs to be squashed with "[IMP] auth_oauth_multi_token: pre-commit auto fixes"

There are also some more commits which should be squashed with the commit above: 

![image](https://github.com/user-attachments/assets/31e569dc-5d2c-484d-8906-41b0d67c09e6)
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

2024-09-30 08:58 UTC, CRogos requested changes
It is important to squash the *.deb removal commit with the commit, where the file was added. Otherwise this large file stays in the git repository.... in this case the commit needs to be squashed with "[IMP] auth_oauth_multi_token: pre-commit auto fixes"

There are also some more commits which should be squashed with the commit above:
![image](https://github.com/user-attachments/assets/7397eaf2-09f9-4677-8185-5c4a400d9ffa)


https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

2025-03-09 12:12 UTC, closed without merging