[18.0][MIG] auth_user_case_insensitive: Migration to 18.0
OCA/server-auth pull request #712
Opened 2024-10-15 16:00 UTC by moncefarajdal

2024-10-15 16:28 UTC, moncefarajdal commented
@dreispt I have migrated the module and tested it locally and it works fine. I'm facing a problem with the test cases. Normally the super()._login method takes login and password but in Odoo 18 it takes a credentials object. I tried modifying the test case to match the new behavior but I can't figure it out.

2025-02-24 13:39 UTC, amh-mw requested changes
1. All the [MIG] commits should be squashed together with the change to the contributors file
2. The [IMP] pre-commit commit is done before any migration changes; see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0#technical-method-to-migrate-a-module-from-170-to-180-branch

2025-03-11 12:27 UTC, JessBrandl reviewed
Agreed with the other review + small improvement in comment

2025-03-11 12:27 UTC, JessBrandl commented on auth_user_case_insensitive/hooks.py
> +
Possible small performance improvement according to the [migration docs](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0)
> You can replace the call to translate a string ( _ ) with self.env._ for getting some performance improvement in some cases. See https://github.com/odoo/odoo/pull/174844.

2025-03-16 19:43 UTC, dreispt approved these changes

2025-03-28 16:29 UTC, CRogos commented
> 1. All the [MIG] commits should be squashed together with the change to the contributors file
> 2. The [IMP] pre-commit commit is done before any migration changes; see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0#technical-method-to-migrate-a-module-from-170-to-180-branch

3. Also squash commits by weblate, OCA-git-bot and oca-ci

2025-08-31 12:17 UTC, closed without merging