16.0 auth saml metadata
OCA/server-auth pull request #739
Opened 2024-12-18 15:48 UTC by dutrieuc

2025-01-13 15:21 UTC, dutrieuc commented
Hello @vincent-hatakeyama,
Should I ping someone for review ?

2025-01-22 13:25 UTC, vincent-hatakeyama requested changes

2025-01-22 13:25 UTC, vincent-hatakeyama commented on auth_saml/models/auth_saml_provider.py
> +            (tuple(provider_ids),),
`provider_ids`is already a tuple, why use tuple again?

2025-01-22 13:26 UTC, vincent-hatakeyama commented
The last 3 commits need to be squashed and their title fixed.

The second commit title also does not match OCA standards.

2025-02-12 17:25 UTC, StefanRijnhart commented
@vincent-hatakeyama Is it OK for you now?

2025-02-13 08:12 UTC, vincent-hatakeyama approved these changes

2025-02-13 09:14 UTC, StefanRijnhart approved these changes
Thanks for the port! Would you like to port this further, at least to 18.0 so that it will be included in future versions from now on?

2025-02-13 09:14 UTC, StefanRijnhart commented
/ocabot merge minor

2025-02-13 09:22 UTC, merged

2025-03-03 10:33 UTC, dutrieuc commented
@StefanRijnhart I'll find some time to add it in 18