[17.0][MIG] auth_oauth_multi_token: Migration to 17.0
OCA/server-auth pull request #742
Opened 2024-12-31 09:33 UTC by kobros-tech

fixing git commits log history with keeping the changes the same for PR #694 this will enable me to migrate to 18.0

2025-01-17 18:11 UTC, timnis commented
Hi @CRogos could this PR merged?

2025-01-18 14:18 UTC, CRogos requested changes
Could you have a look on your commits? Some of them should be squashed, and the last commit should be splitted into: 
[IMP] auth_oauth_multi_token: pre-commit auto fixes
[MIG] auth_oauth_multi_token: Migration to 17.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

![image](https://github.com/user-attachments/assets/4ba160b4-817a-47dd-b3b7-46f6ffcbd152)

Code LGTM, but havn't tested yet.

Do you use odoo.sh? The last time I've tested this module it was not compatible with the login-as function of odoo.sh

2025-01-22 09:48 UTC, timnis commented
Hi @kobros-tech Could you have a look on your commits?

2025-01-22 12:32 UTC, kobros-tech commented
@timnis 
@CRogos 

Hi all, I improved the PR more, and all contributions logs are mentioned.

To have all log preserved here, there was a conflict arised and I guess the first PR was not made correctly as I had to resolve a conflict in another module which is out of scope.

If I git rid of there commits and start on top of last merged commit in version 14.0 or to keep it as it is

2025-01-22 12:55 UTC, kobros-tech commented
@CRogos 
@timnis 

so far so good :)

2025-01-22 16:29 UTC, CRogos commented
@kobros-tech can you squash these commits as well: 
![image](https://github.com/user-attachments/assets/f639f728-50a9-46c8-8c78-29a79afadf12)

also some of your content in the migration commit should be in the "[IMP] auth_oauth_multi_token: pre-commit auto fixes" commit as it was done in the original PR (but without the deb file)

![image](https://github.com/user-attachments/assets/c4ba38cd-b9cc-4adf-8cab-4a0cdd72605d)

2025-01-23 16:24 UTC, kobros-tech commented
@CRogos 

please, make sure that the commit you mentioned that has pandoc file is not there, only the [MIG] commit which is clean as I guess.

I don't understand why should I squash commits done for 16.0 and not for 17.0, could you explain?

2025-01-24 11:11 UTC, CRogos commented
@kobros-tech 
Squashing commits is part of the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0
and there is an extra document, which explains what to squash and how to do it: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

In https://github.com/OCA/server-auth/pull/694 the Commit history is according to the migration guide.
![image](https://github.com/user-attachments/assets/06041fed-4a79-4dc8-89eb-8966ab76d4b2)
But this PR has the issue with the *.deb file, which is a big issue. We need to make sure that this file is not commited in any of the commits. (adding in one commit and removing it in another commit still blows up the repository size)

Nevertheless, the "[IMP] auth_oauth_multi_token: pre-commit auto fixes" commit of https://github.com/OCA/server-auth/pull/694 is correct beside of the *.deb file and should also exist in this PR.

2025-01-24 16:34 UTC, kobros-tech commented
@CRogos 

**I need you to look at the log of commits, because the commit you are talking about is squashed already** and pandoc file is not mentioned or tracked in the migration commit and you can review, thanks!

![Screenshot from 2025-01-24 19-30-35](https://github.com/user-attachments/assets/cc0faac8-9200-4fde-9ceb-78acbf909355)
![Screenshot from 2025-01-24 19-30-54](https://github.com/user-attachments/assets/d00c80cf-ab4e-4086-9f62-c517d400674e)

2025-01-24 16:40 UTC, kobros-tech commented
@CRogos 
If you still are suspecting, I strongly ask you for the commit id that contains pandoc file here and not in other PR as I worked on it and I am quite sure that pandoc file is not tracked at all in this PR branch

2025-01-24 17:12 UTC, CRogos commented
> @CRogos If you still are suspecting, I strongly ask you for the commit id that contains pandoc file here and not in other PR as I worked on it and I am quite sure that pandoc file is not tracked at all in this PR branch

There is no commit with pandoc file, but there is also no commit "[IMP] auth_oauth_multi_token: pre-commit auto fixes" which should be there.

2025-01-24 17:21 UTC, kobros-tech commented
> > @CRogos If you still are suspecting, I strongly ask you for the commit id that contains pandoc file here and not in other PR as I worked on it and I am quite sure that pandoc file is not tracked at all in this PR branch
> 
> There is no commit with pandoc file, but there is also no commit "[IMP] auth_oauth_multi_token: pre-commit auto fixes" which should be there.
> 
> ![image](https://private-user-images.githubusercontent.com/1799080/406526348-cc57b3a0-f5c2-499d-b1df-792719a4f961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3Mzk0MjcsIm5iZiI6MTczNzczOTEyNywicGF0aCI6Ii8xNzk5MDgwLzQwNjUyNjM0OC1jYzU3YjNhMC1mNWMyLTQ5OWQtYjFkZi03OTI3MTlhNGY5NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjRUMTcxODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWUxM2Q1OGZkYmIzZTY2MDA0ZDk3YzBiMTYxYTNiYzI4NGIyNDUxMzNiMTU2NmUxOWVhMzg1MWQzZDBiYmE2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fFW0nqQ_c4mvQ8dHtcgkgUKj3uaDJ8hMAedQUW7whp4)

thanks, now I understand what you mean.

In fact I am not used to make two commits for migration, I have a point of view that I add it in a single commit, I don't mind you if you see it necessary here.

2025-01-24 17:26 UTC, kobros-tech commented
@CRogos 
let me know if I have to divide the commit into two instad of one, so that we get the module merged and get satisfied.

2025-01-24 17:39 UTC, CRogos commented
Yes, that is what I'm trying to explain. You need to split the commit and adapt the commit message.

2025-01-24 18:26 UTC, kobros-tech commented
@CRogos 
two commits are there, clean and out of pandoc tracking

2025-01-24 18:58 UTC, CRogos commented
Better, but could you squash the yellow marked and correct the commit message of the last commit? 
![image](https://github.com/user-attachments/assets/3d91f160-ac6e-4458-91be-6deadcf3d601)

2025-01-24 19:04 UTC, CRogos requested changes

2025-01-24 19:04 UTC, CRogos commented on auth_oauth_multi_token/views/res_users.xml
> +                        <tree limit="10">
This node should be changed to <list

2025-01-24 19:22 UTC, kobros-tech commented on auth_oauth_multi_token/views/res_users.xml
> +                        <tree limit="10">
Is list tag introduced in version 18.0 or version 17.0?

2025-01-24 22:01 UTC, CRogos commented on auth_oauth_multi_token/views/res_users.xml
> +                        <tree limit="10">
you are totally right... got confused, sorry.

2025-01-24 22:01 UTC, CRogos approved these changes

2025-02-03 18:39 UTC, CRogos reviewed
I've now also tested this PR and it is working fine. 

Nevertheless I think a found another issue in this module in the _check_credentials method. 

I also found out, why this module is not working with odoo.sh "login as". I was also able to change this module to make it compatible with odoo.sh by reusing "oauth_access_token" instead of adding "oauth_master_uuid". Neverthless I am not sure if refactoring this module or adding a new module "auth_oauth_multi_token_odoosh" is the right way, because the original solution is cleaner as the patched version?

https://github.com/c4a8-odoo/module-oca-server-auth/commit/d108748b8e2b541b772aace84bf94fbd02393549
https://github.com/c4a8-odoo/module-oca-server-auth/commit/2dc6ccbfecd052df7d711f0499ac4dda0dec61c3

2025-02-03 18:39 UTC, CRogos commented on auth_oauth_multi_token/models/res_users.py
> +                raise
I think we should add an additional check like in the link below.

```
            passwd_allowed = env['interactive'] or not self.env.user._rpc_api_keys_only()
            if passwd_allowed and self.env.user.active:
```

https://github.com/odoo/odoo/blob/10550d9f20f7d08157b4c885d59efb65821ab651/addons/auth_oauth/models/res_users.py#L137-L152

2025-02-04 01:18 UTC, kobros-tech commented on auth_oauth_multi_token/models/res_users.py
> +                raise
@CRogos 

I will add your commit right now the this PR
Any time if you can have access of time, I don't mind if you use and append to our wok.

It is a community and our prior interest is to get something effective.

thanks

2025-02-04 07:44 UTC, CRogos commented on auth_oauth_multi_token/models/res_users.py
> +                raise
@sbidoul I saw your feedback on the v18 migration of this module and I would like to ask you how you think about this change?

https://github.com/OCA/server-auth/pull/742/commits/e6c6427043cd977f8d036063c29a69a9f6c5f1c5

2025-02-04 11:56 UTC, kobros-tech commented on auth_oauth_multi_token/models/res_users.py
> +                raise
I will review it
@kobros-tech

2025-02-05 20:17 UTC, dnplkndll commented on auth_oauth_multi_token/models/res_users.py
> +                raise
this is to allow admin to impersonate? I really like that to verify access. 

I was going to ask about making the provider a one2many too. 
I think would need to be in this module as you might have 2 tokens with 2 providers. the user case would be a multi-company / multi-website each with their own branded oauth login page to match the website / company. if you where to show on each website the sign in for that company. then it needs its only client id and redirect. 
if you have your B2B customers each on their own user no issue. but then the internal users cold not login in anything but one domain/company.

2025-02-06 08:47 UTC, CRogos commented on auth_oauth_multi_token/models/res_users.py
> +                raise
No this is an addon, which i found at a similar case in another documentation (see the link). 
The picked commit after the migration makes it compatible with the Odoo.sh implementation which does the "login as".

2025-02-15 03:58 UTC, dnplkndll approved these changes

2025-02-17 08:13 UTC, CRogos commented
@kobros-tech could you rename the migration commit and squash the yellow marked commits?

![image](https://github.com/user-attachments/assets/2cdb9510-5cc5-4cbc-bb69-0d4edf4c8338)

2025-02-17 10:42 UTC, kobros-tech commented
@CRogos 
can you check the log now?

2025-02-17 10:50 UTC, CRogos commented
@pedrobaeza could you have a look and merge if you agree with the changes.

Regarding the changes related to odoo.sh, I also opened a ticket at Odoo, but they are not willing to change anything on their implementation.

2025-02-17 11:27 UTC, pedrobaeza commented on auth_oauth_multi_token/models/res_users.py
> -        copy=False,
Why are you removing these attributes?

2025-02-17 11:48 UTC, CRogos commented on auth_oauth_multi_token/models/res_users.py
> -        copy=False,
You are right. I thought False is the default, but it is not. @kobros-tech could you please readd the copy=False?

2025-02-17 13:20 UTC, pedrobaeza commented
I need more explanation of the latest commit, and I think it should be out of the migration itself in a separate PR, so we can merge as is the migration, and then discuss about that changes, with steps to reproduce the problem, etc, etc.

2025-02-17 13:39 UTC, kobros-tech commented
ok give me one hour and I will remove the commit

2025-02-17 13:58 UTC, kobros-tech commented
@pedrobaeza 
I removed the last commit

2025-02-17 14:28 UTC, pedrobaeza approved these changes
/ocabot migration auth_oauth_multi_token
/ocabot merge nobump

2025-02-17 14:35 UTC, merged

2025-02-17 16:31 UTC, CRogos commented
Added a new PR regarding the odoo.sh issue https://github.com/OCA/server-auth/pull/764