[MIG] auth_dynamic_groups to v10
OCA/server-auth pull request #96
Opened 2019-05-13 13:23 UTC by hbrunn

2019-05-13 13:25 UTC, hbrunn commented
PS: It's enough to review https://github.com/OCA/server-auth/pull/96/commits/cfc3981a293bd47398c7c76ef03823cc4215984e, everything else already is in v8

2019-05-14 08:50 UTC, NL66278 approved these changes
:+1:  Minor comments, not blocking. Just curious for the motivation to move this from the server-tools repo to server-auth.

Also might still be helpfull to squash adjacent Transifex commits.

2019-05-15 18:23 UTC, tbaden requested changes

2019-05-15 18:23 UTC, tbaden commented on auth_dynamic_groups/views/res_groups.xml
> +    <record model="ir.ui.view" id="view_groups_form">
optional change:
id before model

2019-05-15 18:23 UTC, tbaden commented on auth_dynamic_groups/__manifest__.py
> +    "category": "Tools",
please add the website attribute with the value https://github.com/OCA/server-auth/

2019-05-15 18:23 UTC, tbaden commented on auth_dynamic_groups/__manifest__.py
> +        'python': [],
if you dont use the attribute, just delete it

2019-05-15 18:24 UTC, tbaden commented
thanks for the work 👍 
just some minor details

2019-05-20 07:58 UTC, hbrunn commented
@NL66278 @tbaden thanks, done

2019-05-20 08:18 UTC, tbaden approved these changes
thanks 👍

2019-06-27 07:48 UTC, merged